const fs = require('fs')
function edit(file, change) { const value=fs.readFileSync(file,'utf8'); const next=change(value); if(value===next)throw new Error(`No change in ${file}`);fs.writeFileSync(file,next) }
edit('src/pages/Home.tsx',s=>s.replace('{ newsItems, people, publications, site }','{ newsItems, people, publications, site, appearance }').replace('<div className="hero-cover" aria-hidden="true">','<div className="hero-cover" aria-hidden="true" hidden={!appearance.heroPhoto}>').replace("const featuredPeople = ['vincent-wang','rama-ramamoorthy','yu-wei-chen','sulakshi-heenatigala'].map((id) => people.find((person) => person.id === id)).filter(Boolean) as typeof people",'const featuredPeople = people.slice(0, 4)'))
edit('src/components/layout/Footer.tsx',s=>s.replace('<span className="brand-mark">{contentText("Footer.001")}</span>','{site.logoImage ? <img className="brand-image" src={site.logoImage} alt="" /> : <span className="brand-mark">{contentText("Footer.001")}</span>}'))
edit('src/components/news/NewsCard.tsx',s=>s.replace('<Icon/><span>{item.year}</span>','{item.images?.[0] ? <img src={item.images[0]} alt="" loading="lazy" /> : <Icon/>}<span>{item.year}</span>'))
edit('src/pages/NewsArticle.tsx',s=>s.replace("import ContentGallery from", "import ContentGallery, { ImageGallery } from").replace('<p className="article-lead">{item.summary}</p>','<p className="article-lead">{item.summary}</p><ImageGallery images={(item.images ?? []).map(src => ({src,alt:item.title,caption:\'\'}))} />').replace('item.links.map(', 'item.links.filter(link => link.url).map('))
edit('src/pages/LabLife.tsx',s=>s.replace("import ContentGallery from", "import ContentGallery, { ImageGallery } from").replace('<Icon/><span>{item.year}</span>','{item.images?.[0] ? <img src={item.images[0]} alt={item.title} loading="lazy" /> : <Icon/>}<span>{item.year}</span>').replace('<p>{item.summary}</p></div>','<p>{item.summary}</p><ImageGallery images={(item.images ?? []).slice(1).map(src => ({src,alt:item.title,caption:\'\'}))} /></div>'))
edit('src/pages/Research.tsx',s=>s.replace("import ContentGallery from", "import ContentGallery, { ImageGallery } from").replace('</div></div></Reveal>','</div></div><ImageGallery images={(area.images ?? []).map(src => ({src,alt:area.title,caption:\'\'}))} /></Reveal>'))
edit('src/pages/PersonProfile.tsx',s=>s.replace('person.links.map(', 'person.links.filter(link => link.url).map('))
